# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offence_tracker', '0002_auto_20160909_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='type',
            field=models.CharField(choices=[('RL', 'Late Reporting Time'), ('LONW', 'Learning Objective Not Written'), ('TNH', 'Teaching Not Happening'), ('CCN', 'No Class Control'), ('SMO', 'Students Moving Outside')], max_length=4),
        ),
    ]
