# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offence_tracker', '0003_auto_20160909_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='reporter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
