# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offence_tracker', '0004_auto_20160911_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='grade',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offence',
            name='section',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
