# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offence_tracker', '0005_auto_20160920_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='type',
            field=models.CharField(choices=[(b'RL', b'Late Reporting Time'), (b'LONW', b'Learning Objective Not Written'), (b'TNH', b'Teaching Not Happening'), (b'CCN', b'No Class Control'), (b'SMO', b'Students Moving Outside'), (b'NHE', b'No Happiness Exercise')], max_length=4),
        ),
    ]
